### ISSUE TITLE
Hitting Command+0 in Firefox causes the page footer to move

### ISSUE THREAD

**Issue by disambiguator** [codeforamerica/cfa-styleguide-gem#14]
In Firefox, when you press command 0, the footer jumps to the bottom of the view, but then does not stay there on scroll, causing the footer to block content on the page. Here's a screenshot:

![image](https://user-images.githubusercontent.com/2306794/47458690-0771e500-d78f-11e8-81af-9593ca40f505.png)

**Comment by hartsick** [comment]
I've just tried this out on https://demo.getcalfresh.org and https://demo.reportchangescolorado.org and can't reproduce! Closing since it seems we've addressed.
