### ISSUE TITLE
Allow for overriding variables

### ISSUE THREAD

**Issue by hartsick** [codeforamerica/cfa-styleguide-gem#17]
Right now, the styleguide does not allow for easily overriding base variables (in `atoms/variables`) because we guide people to import the styleguide as one file.

Right now we guide users to override styles by doing the following in their `application.scss`:
```
@import 'cfa_styleguide_main';
@import 'overrides';
```
However, if you place variables into the overrides file or do something like:
```
@import 'cfa_styleguide_main';
@import `variables`;
@import 'overrides';
```
The overridden variables won't be picked up because the new variables aren't imported before the styleguide scss is compiled.

Instead, we need something like:
```
@import `cfa_styleguide_main/variables;
@import `overrides/variables`;
@import `cfa_styleguide_main/all-else;
@import `overrides/all-else;
```
This could mean a more flexible import structure generally (right now we don't give an option between requiring everything as `cfa_styleguide_main` and requiring every styleguide file yourself), or just breaking out the variables file.

**Comment by bensheldon** [comment]
I think we can achieve something similar using the `!default` declaration inside of the styleguides variables file: https://robots.thoughtbot.com/sass-default

I'm fairly certain that would allow us to specify:

```scss
@import "overrides/variables";
@import "cfa_styleguide_main";
```

I found this when looking through the [bootstrap-sass gem](https://github.com/twbs/bootstrap-sass/blob/master/assets/stylesheets/bootstrap/_variables.scss) achieves this functionality.

**Comment by hartsick** [comment]
Done! Thanks, @bengolder & @bensheldon !
