### ISSUE TITLE
Form cards are missing top border

### ISSUE THREAD

**Issue by disambiguator** [codeforamerica/cfa-styleguide-gem#2]
The GCF styleguide gives all their cards with a top border, as shown at: https://www.getcalfresh.org/styleguide

We've solved this for form cards by adding this to our custom scss, but it should just be there by default.
```
.form-card {
  border-top: 8px solid $color-tan;
}
```

**Comment by hartsick** [comment]
Working on updating the styleguide with latest code from GCF! We had a good talk with GCF and they're going to look into moving to the gem in the near future.

**Comment by hartsick** [comment]
@disambiguator this should be resolved now—try updating your gem and let me know!

**Comment by disambiguator** [comment]
Yup, it works! :)

**Comment by hartsick** [comment]
Yay!
