### ISSUE TITLE
Update form organisms 

### ISSUE THREAD

**Issue by norrishung** [codeforamerica/cfa-styleguide-gem#22]
We have mostly converged on different types of "Form cards" that we use across form-based products. We may want to identify the ones we consistently use and add them to the style guide for reference. For example:

1. Sign-posts
2. Simple centered form cards
3. Complex left-aligned form cards
4. Confirmation pages
5. Document upload/photo pages

**Comment by hartsick** [comment]
I'm going to close this in favor of the related issue where we've included your designs!
