### ISSUE TITLE
Create an emoji index

### ISSUE THREAD

**Issue by anule** [codeforamerica/cfa-styleguide-gem#24]
Create an emoji index for quick reference when adding new views. Currently difficult to find/access necessary emojis

**Comment by hartsick** [comment]
I think for this, we could add a new slab to the main styleguide reference page (/cfa/styleguide) that features all of the emoji that are included in the styleguide.

It'd be nice to have this be programmatically made so we can minimize the amount of manual updates needed. It also would be great to let us see which emoji are GCF-specific and could be removed (in https://github.com/codeforamerica/cfa-styleguide-gem/issues/6).

**Comment by hartsick** [comment]
Whitney: interested in developing more consistency in name (name vs hex code), which would allow this to be searched easily.

Zak: would like to include the full set of EmojiOne emoji.

**Comment by anule** [comment]
- [ ] Add complete EmojiOne set
- [ ] Standardize emoji sizes
- [ ] Add associated class name labels to the emojis
- [ ] Add emoji size chart
