### ISSUE TITLE
Fix reveal pattern code

### ISSUE THREAD

**Issue by norrishung** [codeforamerica/cfa-styleguide-gem#43]
The reveal pattern currently has an extra `<div class="notice">` wrapper that puts the content in a blue background. This is not necessary or desirable for the pattern! It should look like this:

<img width="520" alt="screen shot 2018-12-21 at 10 26 28 am" src="https://user-images.githubusercontent.com/606439/50357447-e289bc00-050a-11e9-90c4-2e1ceb6cbe90.png">

Not like this:

<img width="795" alt="screen shot 2018-12-21 at 10 26 49 am" src="https://user-images.githubusercontent.com/606439/50357479-ee757e00-050a-11e9-89e8-82e6ca72427d.png">

**Comment by hartsick** [comment]
Looks like this was fixed when Ben pulled the reveal code into an example partial!
