### ISSUE TITLE
Explore screenshot testing

### ISSUE THREAD

**Issue by hartsick** [codeforamerica/cfa-styleguide-gem#51]
To help us understand when we're making changes to the styleguide and verifying that those changes are intentional, it might be helpful to implement some form of visual diffing on the styleguide that we can look at when reviewing pull requests.

This story is to explore how we might implement screenshot testing and come up with proposal(s) for how to integrate it into our application.

One option to do this might be Happo.io, whose maintainer Henric came to speak to CfA at end of 2017. Notes from that conversation are below:

---

To start, we could set up Happo on our [main styleguide page](https://github.com/codeforamerica/cfa-styleguide-gem/blob/master/app/views/cfa/styleguide/pages/index.html.erb) and programmatically pull components from the [`examples` directory](https://github.com/codeforamerica/cfa-styleguide-gem/tree/master/app/views/examples) we currently use to build the HTML. It will include some things (for example, buttons) in one diff when they're actually different components, but should be good to start. He mentioned that other companies usually have some grouping of components.

The main thing he flagged is that we'll need to grab the precompiled CSS before running Happo. @tdooner mentioned they used to do this when they worked together at Brigade. Henric also mentioned he used to work in Ruby/Rails in past, and would be interested in working with us to help get set up. I (Christa) and Tom both have his contact information for anyone interested in exploring this more.

In future, we could potentially spin up multiple environments with each of the apps using the styleguide and test against them.

**Comment by hartsick** [comment]
Percy just announced a free tier that we might want to try out: https://percy.io/?sponsorednewsletter&utm_source=rubyweekly&utm_medium=sponsored_newsletter&utm_campaign=190222&utm_term=primary (h/t Ben Sheldon)

**Comment by bensheldon** [comment]
I'm working on setting up Percy 🏗

**Comment by hartsick** [comment]
I'm going to declare this done for now, since we have Percy running. Nice work!
