### ISSUE TITLE
Make styleguide Sass variables available for use in host application

### ISSUE THREAD

**Issue by hartsick** [codeforamerica/cfa-styleguide-gem#55]
Currently, you can only use the CfA Styleguide Sass variables (e.g. colors, pixel sizes, etc.) within the styleguide CSS. It would be useful to have [these variables](https://github.com/codeforamerica/cfa-styleguide-gem/blob/master/app/assets/stylesheets/atoms/_variables.scss) available for use inside the host application, so that I could write something like `font-size: $font-size-normal` in my project's CSS.

@zaksoup has said that not having this has been a pain point for both Clear My Record and ClientComm, so he may be good person to talk to while developing the feature.

This feature is similar to https://github.com/codeforamerica/cfa-styleguide-gem/issues/17, which would allow host applications to override styleguide Sass variables.

**Comment by zaksoup** [comment]
👍 I can confirm - CMR team's `application.scss` did not have the `*= require_tree .` directive and variables worked for me just now with no other code changes.
