### ISSUE TITLE
Audit styleguide references to find unused pages

### ISSUE THREAD

**Issue by hartsick** [codeforamerica/cfa-styleguide-gem#58]
Right now we have a handful of reference styleguide pages, and we suspect all of them are not in active use.

* https://cfa-styleguide.herokuapp.com/cfa/styleguide [Known in-use]
* https://cfa-styleguide.herokuapp.com/cfa/styleguide/form-builder [Known in-use]
* https://cfa-styleguide.herokuapp.com/cfa/styleguide/cbo-dashboard [???]
* https://cfa-styleguide.herokuapp.com/cfa/styleguide/cbo-analytics [???]
* https://cfa-styleguide.herokuapp.com/cfa/styleguide/current [???!]
* https://cfa-styleguide.herokuapp.com/cfa/styleguide/custom-docs [???]

GCF would be the only app to use them, if they're actually being used. @anule could you do some investigating and let us know which of these pages should be kept? Thanks!

**Comment by anule** [comment]
In some way or another, all of these styles are being used. 

In-use in this form:
CBO dashboard: https://cfa-styleguide.herokuapp.com/cfa/styleguide/cbo-dashboard
CBO analytics: https://cfa-styleguide.herokuapp.com/cfa/styleguide/cbo-analytics

Changes on the 'Current' page (https://cfa-styleguide.herokuapp.com/cfa/styleguide/current):
- 'The legal stuff' page as a sort-of iframe (not an iframe, but reminds me of one) where all the legal information is displayed
<img width="728" alt="screen shot 2019-01-16 at 4 13 23 pm" src="https://user-images.githubusercontent.com/27640736/51286899-e2fe6100-19a9-11e9-8f45-2c388481a16e.png">

Most of the custom docs (https://cfa-styleguide.herokuapp.com/cfa/styleguide/custom-docs) are being used, though some styles have been retired. Specifically:
- The 'Proof of Labor' card
- The 'Proof of Job' card
- The dots at the bottom of the guided documents yes/no screens

**Comment by hartsick** [comment]
Thanks, @anule! This is helpful.

I'd like to propose deleting the current page because I don't think it's a needed reference—if we need it, can just go to the GCF site (and it's not yet relevant for the other projects). The other projects treat legal agreements differently at the moment.

I'm also inclined to delete the custom docs page, since it doesn't seem that it's used as a reference by GCF (form card structure is outdated—the dots). The aim would be to replace this page eventually with a form card partial or layout that teams can just include in their app, rather than using page as reference.

What do you think?

**Comment by norrishung** [comment]
related to #65 

I agree with Christa that all of those pages can be deleted. Anule, those pages were created as an HTML reference for engineers as they were working on those features in GCF in the past. I don't think they need to be referenced anymore.
