### ISSUE TITLE
When a designer/engineer looks at the reference, they see and understand everything the styleguide has to offer

### ISSUE THREAD

**Issue by hartsick** [codeforamerica/cfa-styleguide-gem#79]
Some common threads came up in our planning session, including a desire to have more of the styleguide's functionality documented, improving navigation and layout in the [styleguide reference](https://cfa-styleguide.herokuapp.com), and making it an onboarding resource for both engineers and designers.

Some questions:
* What documentation would be helpful that is currently missing?
* What would make the styleguide reference more useable?
* What additional information besides basic documentation would we need to make this an onboarding resource?

Some issues/concrete actions that have been proposed:
* https://github.com/codeforamerica/cfa-styleguide-gem/issues/53: Links to components on reference page
* Continuing to extract atoms and molecules into partials/components, and including their usage on the reference page (see "Labels" section on [styleguide reference](https://cfa-styleguide.herokuapp.com)

Discuss!

The goal of this issue is to identify and break out some actionable stories from the discussion that follows.

[source: [2/7/2019 WG meeting](https://app.mural.co/t/multibenefitspartnership6801/m/multibenefitspartnership6801/1549558756078/a4bd4ea0f111a73a774ea7ae2e0e49eab7c46b67)]

**Comment by racheledelman** [comment]
I would find it helpful to have sidebar navigation where I can see all of the elements listed at a glance and jump to them: Bootstrap example:
![image](https://user-images.githubusercontent.com/2693690/52506684-26607f80-2ba4-11e9-9fd6-0de2211000fb.png)

This might be best achieved by also breaking up the main page into a few different pages. Maybe one each for atoms, molecules, and organisms?

One challenge is: how can we better show the relationship between atoms and molecules?

One example of this is `Example pills`. It's listed under atoms like this:
![image](https://user-images.githubusercontent.com/2693690/52506453-7be85c80-2ba3-11e9-8bdd-fd01df90b3e1.png)

Then you scroll down a screen and see it under molecules like this:
![image](https://user-images.githubusercontent.com/2693690/52506437-712dc780-2ba3-11e9-9bea-524d30f1487d.png)

Are these serving two different purposes? Should we demonstrate every atom as part of a molecule? Do they need to be linked together in some way? I think it would be easy for a user to see the atom and miss the additional context of the molecules. OTOH, if the molecules are just examples and not prescriptive, maybe that doesn't matter.
