### ISSUE TITLE
Update emoji licensing in README

### ISSUE THREAD

**Issue by anule** [codeforamerica/cfa-styleguide-gem#98]
EmojiOne has rebranded to JoyPixels and republished their licensing tiers. Check that we are in compliance and update the README to reflect those findings

Our current license: EmojiOne 3.1 Nonprofit Premium

New licensing tiers: https://www.joypixels.com/licenses)

**Comment by norrishung** [comment]
Perhaps consider https://openmoji.org

=)

**Comment by hartsick** [comment]
This brought up another conversation: we should consider moving to an open source or free emoji set in the future (or one that we've created!).

**Comment by hartsick** [comment]
We are still using the EmojiOne 2.1 Nonprofit Premium and have licensed it under that set. If we decided to upgrade and use the newer set under the rebrand then I think we would update the license then.
